# fish completion for crom
complete -c crom -f -a "(__fish_complete_directories)"

complete -c crom -s n -l name           -r -d 'filename pattern'
complete -c crom -s g -l glob           -r -d 'match the whole name'
complete -c crom -s i -l ignore-case       -d 'fold case'
complete -c crom      -l case-sensitive    -d 'match as typed'
complete -c crom -s E -l exclude        -r -d 'skip names matching glob'
complete -c crom -s c -l content        -r -d 'search file contents'
complete -c crom -s t -l type           -x -a 'f\t"regular file" d\tdirectory l\tsymlink' -d 'filter by type'
complete -c crom -s s -l size           -r -d 'filter by size, [+-]N'
complete -c crom -s H -l hidden            -d 'include dot entries'
complete -c crom -s u -l unrestricted      -d 'hidden and no ignore files'
complete -c crom -s L -l follow            -d 'follow symlinked directories'
complete -c crom      -l depth          -r -d 'max recursion depth'
complete -c crom      -l max-results    -r -d 'stop after N matches'
complete -c crom -s e -l exec           -r -d 'run command per result, {} is the path'
complete -c crom -s j -l threads        -r -d 'worker threads'
complete -c crom -s a -l text              -d 'search binary files too'
complete -c crom -s 0 -l null              -d 'NUL-separated output'
complete -c crom      -l json              -d 'JSON output'
complete -c crom      -l bar               -d 'progress bar'
complete -c crom -s q -l no-bar            -d 'no progress bar'
complete -c crom      -l no-ignore         -d 'do not read .gitignore'
complete -c crom      -l no-messages       -d 'do not report unreadable paths'
complete -c crom      -l no-config         -d 'skip ~/.cromrc'
complete -c crom      -l color          -x -a 'auto always never' -d 'when to colour'
complete -c crom -s h -l help              -d 'show help'
complete -c crom -s V -l version           -d 'print version'
